version: "2"
services:
  backend-test:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=test
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /var/mongodb
    ports:
      - "27017:27017"
